# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: Prepare build environment
description: Setup Node.js & pnpm
inputs:
  node-version:
    description: Define Node.js version
    required: false
    default: "24"
  pnpm-version:
    description: Define pnpm version
    required: false
    default: ""
  using-local-renovate:
    description: if true, using package.json renovate
    required: false
    default: "false"
  renovate-config-file:
    description: "Set renovate.global.json path (Default: .github/renovate.global.json)"
    required: false
    default: .github/renovate.global.json
  renovate-token:
    description: Set GitHub Personal Access Token using Renovate
    required: true
  dry-run:
    description: if true, dry run renovate
    required: false
    default: "false"


runs:
  using: composite
  steps:
    - name: Setup pnpm with explicit version
      if: ${{ inputs.pnpm-version != '' }}
      uses: pnpm/action-setup@v6
      with:
        version: ${{ inputs.pnpm-version }}

    - name: Setup pnpm
      if: ${{ inputs.pnpm-version == '' }}
      uses: pnpm/action-setup@v6

    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node-version }}
        cache: "pnpm"

    - name: Run npm renovate
      if: ${{ inputs.using-local-renovate == 'true' }}
      shell: bash
      run: pnpm exec renovate
      env:
        RENOVATE_CONFIG_FILE: ${{ inputs.renovate-config-file }}
        RENOVATE_TOKEN: ${{ inputs.renovate-token }}
        RENOVATE_HOST_RULES: '[{"hostType":"npm","matchHost":"https://npm.pkg.github.com/","token":"${{ inputs.renovate-token }}"}]'
        RENOVATE_DRY_RUN: ${{ inputs.dry-run }}
        RENOVATE_GIT_AUTHOR: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

    - name: pnpm dlx renovate
      if: ${{ inputs.using-local-renovate == 'false' }}
      shell: bash
      run: pnpm dlx --allow-build={better-sqlite3,core-js-pure,dtrace-provider,protobufjs,protobufjs,re2} renovate@^43 --help
      env:
        RENOVATE_CONFIG_FILE: ${{ inputs.renovate-config-file }}
        RENOVATE_TOKEN: ${{ inputs.renovate-token }}
        RENOVATE_HOST_RULES: '[{"hostType":"npm","matchHost":"https://npm.pkg.github.com/","token":"${{ inputs.renovate-token }}"}]'
        RENOVATE_DRY_RUN: ${{ inputs.dry-run }}
        RENOVATE_GIT_AUTHOR: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
